app:
  jwt:
    jwtkey: "saleiwacn;j"
  mysql:
    dsn: root:wang109097@tcp(127.0.0.1:3306)/crocodile?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
    maxIdleConnection: 100
    maxOpenConnection: 100
    maxQueryTime: 10
  etcd:
    endpoints: ["127.0.0.1:2379"]
    dialTimeout: 5000
    username:
    password:
  gin:
    mode: debug
  executor:
    # 运行任务的broker 端口
    #address: ":56272"
  log:
    level: DEBUG
    path:
    size: 10
